/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package io.sindri.generator.ast.container;

import io.sindri.generator.abstract_.AstFileGenerator;
import io.sindri.generator.container.contract.ContainerDataFileGeneratorContract;
import io.sindri.generator.enum_.GenerateStatus;
import java.util.Map;

public class AstContainerDataFileGenerator extends AstFileGenerator
        implements ContainerDataFileGeneratorContract {

    @Override
    public GenerateStatus generateFile(
            String directory,
            String className,
            String namespace,
            Map<String, String[]> publishers) {
        String contents = buildFileContents(namespace, className, buildCallbacksBody(publishers));
        return writeFile(directory, className, contents);
    }

    protected String buildFileContents(String namespace, String className, String callbacksBody) {
        return """
                /*
                 * This file was automatically generated by Sindri.
                 * Do not edit manually.
                 */

                package %NAMESPACE%;

                import io.valkyrja.container.data.contract.ContainerDataContract;
                import io.valkyrja.container.manager.contract.ContainerContract;

                import java.util.Map;
                import java.util.function.BiFunction;
                import java.util.function.Consumer;

                public record %CLASSNAME%() implements ContainerDataContract {

                    @Override
                    public Map<Class<?>, Class<?>> aliases() {
                        return Map.of();
                    }

                    @Override
                    public Map<Class<?>, Consumer<ContainerContract>> callbacks() {
                %CALLBACKS%
                    }

                    @Override
                    public Map<Class<?>, BiFunction<ContainerContract, Map<String, Object>, Object>> services() {
                        return Map.of();
                    }

                    @Override
                    public Map<Class<?>, Class<?>> singletons() {
                        return Map.of();
                    }
                }
                """
                .replace("%NAMESPACE%", namespace)
                .replace("%CLASSNAME%", className)
                .replace("%CALLBACKS%", callbacksBody);
    }

    @Override
    public String generateClassContents(Map<String, String[]> publishers) {
        return buildCallbacksBody(publishers);
    }

    protected String buildCallbacksBody(Map<String, String[]> publishers) {
        if (publishers.isEmpty()) {
            return "        return Map.of();";
        }
        if (publishers.size() <= 10) {
            StringBuilder sb = new StringBuilder("        return Map.of(\n");
            int i = 0;
            for (Map.Entry<String, String[]> entry : publishers.entrySet()) {
                String serviceFqn = entry.getKey();
                String[] ref = entry.getValue();
                sb.append("            ")
                        .append(serviceFqn)
                        .append(".class, ")
                        .append(ref[0])
                        .append("::")
                        .append(ref[1]);
                if (i < publishers.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
                i++;
            }
            sb.append("        );");
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder("        return Map.ofEntries(\n");
        int i = 0;
        for (Map.Entry<String, String[]> entry : publishers.entrySet()) {
            String serviceFqn = entry.getKey();
            String[] ref = entry.getValue();
            sb.append("            Map.entry(")
                    .append(serviceFqn)
                    .append(".class, ")
                    .append(ref[0])
                    .append("::")
                    .append(ref[1])
                    .append(")");
            if (i < publishers.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
            i++;
        }
        sb.append("        );");
        return sb.toString();
    }
}
