/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package io.sindri.generator.ast.event;

import io.sindri.generator.abstract_.AstFileGenerator;
import io.sindri.generator.enum_.GenerateStatus;
import io.sindri.generator.event.contract.EventDataFileGeneratorContract;
import java.util.Map;

public class AstEventDataFileGenerator extends AstFileGenerator
        implements EventDataFileGeneratorContract {

    @Override
    public GenerateStatus generateFile(
            String directory, String className, String namespace, Map<String, String> listeners) {
        String contents = buildFileContents(namespace, className, buildListenersBody(listeners));
        return writeFile(directory, className, contents);
    }

    protected String buildFileContents(String namespace, String className, String listenersBody) {
        return """
                /*
                 * This file was automatically generated by Sindri.
                 * Do not edit manually.
                 */

                package %NAMESPACE%;

                import io.valkyrja.event.data.contract.EventDataContract;
                import io.valkyrja.event.data.contract.ListenerContract;

                import java.util.Map;

                public record %CLASSNAME%() implements EventDataContract {

                    @Override
                    public Map<Class<?>, Map<String, String>> events() {
                        return Map.of();
                    }

                    @Override
                    public Map<String, ListenerContract> listeners() {
                        %LISTENERS%
                    }
                }
                """
                .replace("%NAMESPACE%", namespace)
                .replace("%CLASSNAME%", className)
                .replace("%LISTENERS%", listenersBody);
    }

    @Override
    public String generateClassContents(Map<String, String> listeners) {
        return buildListenersBody(listeners);
    }

    protected String buildListenersBody(Map<String, String> listeners) {
        if (listeners.isEmpty()) {
            return "return Map.of();";
        }
        if (listeners.size() <= 10) {
            StringBuilder sb = new StringBuilder("return Map.of(\n");
            int i = 0;
            for (Map.Entry<String, String> entry : listeners.entrySet()) {
                sb.append("            \"")
                        .append(entry.getKey())
                        .append("\", ")
                        .append(entry.getValue());
                if (i < listeners.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
                i++;
            }
            sb.append("        );");
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder("return Map.ofEntries(\n");
        int i = 0;
        for (Map.Entry<String, String> entry : listeners.entrySet()) {
            sb.append("            Map.entry(\"")
                    .append(entry.getKey())
                    .append("\", ")
                    .append(entry.getValue())
                    .append(")");
            if (i < listeners.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
            i++;
        }
        sb.append("        );");
        return sb.toString();
    }
}
