/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

package io.sindri.generator.abstract_;

import io.sindri.generator.enum_.GenerateStatus;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.Objects;

public abstract class AstFileGenerator {

    /**
     * Render a {@code routes()} method body from a name → supplier-expression map: an inline {@code
     * Map.of(...)} for up to ten entries, or {@code Map.ofEntries(...)} beyond. Shared by every
     * routing-data generator (CLI, HTTP, gRPC).
     */
    protected String buildRoutesBody(Map<String, String> routes) {
        if (routes.isEmpty()) {
            return "        return Map.of();";
        }
        if (routes.size() <= 10) {
            StringBuilder sb = new StringBuilder("        return Map.of(\n");
            int i = 0;
            for (Map.Entry<String, String> entry : routes.entrySet()) {
                sb.append("            \"")
                        .append(entry.getKey())
                        .append("\", ")
                        .append(entry.getValue());
                if (i < routes.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
                i++;
            }
            sb.append("        );");
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder("        return Map.ofEntries(\n");
        int i = 0;
        for (Map.Entry<String, String> entry : routes.entrySet()) {
            sb.append("            Map.entry(\"")
                    .append(entry.getKey())
                    .append("\", ")
                    .append(entry.getValue())
                    .append(")");
            if (i < routes.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
            i++;
        }
        sb.append("        );");
        return sb.toString();
    }

    /**
     * Render a complete routing-data source file for a map-lookup protocol (CLI, gRPC): a record
     * implementing the module's {@code *RoutingDataContract} with a single {@code routes()} method.
     * The module segment and contract name are parameterized so every such generator shares one
     * template.
     */
    protected String buildRoutesDataFile(
            String namespace,
            String className,
            String routesBody,
            String module,
            String dataContract) {
        return """
                /*
                 * This file was automatically generated by Sindri.
                 * Do not edit manually.
                 */

                package %NAMESPACE%;

                import io.valkyrja.%MODULE%.routing.data.contract.%DATA_CONTRACT%;
                import io.valkyrja.%MODULE%.routing.data.contract.RouteContract;

                import java.util.Map;
                import java.util.function.Supplier;

                public record %CLASSNAME%() implements %DATA_CONTRACT% {

                    @Override
                    public Map<String, Supplier<RouteContract>> routes() {
                %ROUTES%
                    }
                }
                """
                .replace("%NAMESPACE%", namespace)
                .replace("%MODULE%", module)
                .replace("%DATA_CONTRACT%", dataContract)
                .replace("%CLASSNAME%", className)
                .replace("%ROUTES%", routesBody);
    }

    protected GenerateStatus writeFile(String directory, String className, String data) {
        String filePath = directory.replaceAll("/+$", "") + "/" + className + ".java";
        Path path = Paths.get(filePath);
        try {
            Path parent = path.getParent();
            Files.createDirectories(Objects.requireNonNullElse(parent, Paths.get(".")));
            String existing =
                    Files.exists(path) ? Files.readString(path, StandardCharsets.UTF_8) : null;
            if (data.equals(existing)) {
                return GenerateStatus.SKIPPED;
            }
            Files.writeString(path, data, StandardCharsets.UTF_8);
            return GenerateStatus.SUCCESS;
        } catch (IOException e) {
            return GenerateStatus.FAILURE;
        }
    }
}
