/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package io.sindri.generator.ast.http;

import io.sindri.ast.data.HttpRouteData;
import io.sindri.generator.abstract_.AstFileGenerator;
import io.sindri.generator.enum_.GenerateStatus;
import io.sindri.generator.http.contract.HttpDataFileGeneratorContract;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class AstHttpDataFileGenerator extends AstFileGenerator
        implements HttpDataFileGeneratorContract {

    @Override
    public GenerateStatus generateFile(
            String directory,
            String className,
            String namespace,
            Map<String, String> routes,
            Map<String, HttpRouteData> routeData) {
        String contents =
                buildFileContents(
                        namespace,
                        className,
                        buildRoutesBody(routes, routeData),
                        buildPathsBody(routeData, false),
                        buildPathsBody(routeData, true));
        return writeFile(directory, className, contents);
    }

    protected String buildFileContents(
            String namespace,
            String className,
            String routesBody,
            String pathsBody,
            String dynamicPathsBody) {
        return """
                /*
                 * This file was automatically generated by Sindri.
                 * Do not edit manually.
                 */

                package %NAMESPACE%;

                import io.valkyrja.http.routing.data.contract.HttpRoutingDataContract;
                import io.valkyrja.http.routing.data.contract.RouteContract;

                import java.util.Map;
                import java.util.function.Supplier;

                public record %CLASSNAME%() implements HttpRoutingDataContract {

                    @Override
                    public Map<String, Supplier<RouteContract>> routes() {
                %ROUTES%
                    }

                    @Override
                    public Map<String, Map<String, String>> paths() {
                %PATHS%
                    }

                    @Override
                    public Map<String, Map<String, String>> dynamicPaths() {
                %DYNAMIC_PATHS%
                    }

                    @Override
                    public Map<String, Map<String, String>> regexes() {
                        return Map.of();
                    }
                }
                """
                .replace("%NAMESPACE%", namespace)
                .replace("%CLASSNAME%", className)
                .replace("%ROUTES%", routesBody)
                .replace("%PATHS%", pathsBody)
                .replace("%DYNAMIC_PATHS%", dynamicPathsBody);
    }

    @Override
    public String generateClassContents(
            Map<String, String> routes, Map<String, HttpRouteData> routeData) {
        return buildRoutesBody(routes, routeData);
    }

    protected String buildRoutesBody(
            Map<String, String> routes, Map<String, HttpRouteData> routeData) {
        if (routes.isEmpty()) {
            return "        return Map.of();";
        }
        if (routes.size() <= 10) {
            StringBuilder sb = new StringBuilder("        return Map.of(\n");
            int i = 0;
            for (Map.Entry<String, String> entry : routes.entrySet()) {
                sb.append("            \"")
                        .append(entry.getKey())
                        .append("\", ")
                        .append(entry.getValue());
                if (i < routes.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
                i++;
            }
            sb.append("        );");
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder("        return Map.ofEntries(\n");
        int i = 0;
        for (Map.Entry<String, String> entry : routes.entrySet()) {
            sb.append("            Map.entry(\"")
                    .append(entry.getKey())
                    .append("\", ")
                    .append(entry.getValue())
                    .append(")");
            if (i < routes.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
            i++;
        }
        sb.append("        );");
        return sb.toString();
    }

    protected String buildPathsBody(Map<String, HttpRouteData> routeData, boolean dynamic) {
        Map<String, Map<String, String>> methodToPathMap = new LinkedHashMap<>();
        for (HttpRouteData route : routeData.values()) {
            boolean isDynamic = route.path().contains("{");
            if (isDynamic != dynamic) {
                continue;
            }
            for (String method : route.requestMethods()) {
                if (method.equals("HEAD")) {
                    continue;
                }
                methodToPathMap
                        .computeIfAbsent(method, k -> new LinkedHashMap<>())
                        .put(route.path(), route.name());
            }
        }

        if (methodToPathMap.isEmpty()) {
            return "        return Map.of();";
        }

        List<String> methodEntries = new ArrayList<>();
        for (Map.Entry<String, Map<String, String>> methodEntry : methodToPathMap.entrySet()) {
            String method = methodEntry.getKey();
            Map<String, String> pathMap = methodEntry.getValue();
            String innerMap = buildInnerPathMap(pathMap);
            methodEntries.add("            Map.entry(\"" + method + "\", " + innerMap + ")");
        }

        StringBuilder sb = new StringBuilder("        return Map.ofEntries(\n");
        for (int i = 0; i < methodEntries.size(); i++) {
            sb.append(methodEntries.get(i));
            if (i < methodEntries.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
        }
        sb.append("        );");
        return sb.toString();
    }

    protected String buildInnerPathMap(Map<String, String> pathMap) {
        if (pathMap.isEmpty()) {
            return "Map.of()";
        }
        if (pathMap.size() <= 10) {
            StringBuilder sb = new StringBuilder("Map.of(");
            int i = 0;
            for (Map.Entry<String, String> e : pathMap.entrySet()) {
                sb.append("\"")
                        .append(e.getKey())
                        .append("\", \"")
                        .append(e.getValue())
                        .append("\"");
                if (i < pathMap.size() - 1) {
                    sb.append(", ");
                }
                i++;
            }
            sb.append(")");
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder("Map.ofEntries(");
        int i = 0;
        for (Map.Entry<String, String> e : pathMap.entrySet()) {
            sb.append("Map.entry(\"")
                    .append(e.getKey())
                    .append("\", \"")
                    .append(e.getValue())
                    .append("\")");
            if (i < pathMap.size() - 1) {
                sb.append(", ");
            }
            i++;
        }
        sb.append(")");
        return sb.toString();
    }
}
