/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package io.sindri.generator.ast.cli;

import io.sindri.generator.abstract_.AstFileGenerator;
import io.sindri.generator.cli.contract.CliDataFileGeneratorContract;
import io.sindri.generator.enum_.GenerateStatus;
import java.util.Map;

public class AstCliDataFileGenerator extends AstFileGenerator
        implements CliDataFileGeneratorContract {

    @Override
    public GenerateStatus generateFile(
            String directory, String className, String namespace, Map<String, String> routes) {
        String contents = buildFileContents(namespace, className, buildRoutesBody(routes));
        return writeFile(directory, className, contents);
    }

    protected String buildFileContents(String namespace, String className, String routesBody) {
        return """
                /*
                 * This file was automatically generated by Sindri.
                 * Do not edit manually.
                 */

                package %NAMESPACE%;

                import io.valkyrja.cli.routing.data.contract.CliRoutingDataContract;
                import io.valkyrja.cli.routing.data.contract.RouteContract;

                import java.util.Map;
                import java.util.function.Supplier;

                public record %CLASSNAME%() implements CliRoutingDataContract {

                    @Override
                    public Map<String, Supplier<RouteContract>> routes() {
                %ROUTES%
                    }
                }
                """
                .replace("%NAMESPACE%", namespace)
                .replace("%CLASSNAME%", className)
                .replace("%ROUTES%", routesBody);
    }

    @Override
    public String generateClassContents(Map<String, String> routes) {
        return buildRoutesBody(routes);
    }

    protected String buildRoutesBody(Map<String, String> routes) {
        if (routes.isEmpty()) {
            return "        return Map.of();";
        }
        if (routes.size() <= 10) {
            StringBuilder sb = new StringBuilder("        return Map.of(\n");
            int i = 0;
            for (Map.Entry<String, String> entry : routes.entrySet()) {
                sb.append("            \"")
                        .append(entry.getKey())
                        .append("\", ")
                        .append(entry.getValue());
                if (i < routes.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
                i++;
            }
            sb.append("        );");
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder("        return Map.ofEntries(\n");
        int i = 0;
        for (Map.Entry<String, String> entry : routes.entrySet()) {
            sb.append("            Map.entry(\"")
                    .append(entry.getKey())
                    .append("\", ")
                    .append(entry.getValue())
                    .append(")");
            if (i < routes.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
            i++;
        }
        sb.append("        );");
        return sb.toString();
    }
}
